# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs



on:
  push:
    branches:
      - dev
      - develop
  pull_request:
    branches:
      - dev
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache Cypress Binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-

      - name: Delete Cypress Cache (if needed)
        run: rm -rf ~/.cache/Cypress || true    

      - name: Install dependencies
        run: npm install

      - name: Fix Cypress Permissions
        run: chmod +x ./node_modules/.bin/cypress || true

      - name: Install Cypress Binary
        run: npx cypress install

      - name: Fix Cypress Permissions
        run: chmod +x ./node_modules/.bin/cypress

      - name: Install Cypress
        run: npx cypress install

      - name: Clear Cypress Cache
        run: ./node_modules/.bin/cypress cache clear

      - name: Run Cypress tests in headless Chrome
        run: npx cypress run --browser chrome --headless --config defaultCommandTimeout=10000

